server:
  port: 9003
spring:
  application:
    name: manage-service
# feign
feign:
  client:
    config:
      default:
        #连接超时时间
        connectTimeout: 20000
        #读取超时时间
        readTimeout: 20000
        loggerLevel: basic
  hystrix:
    enabled: true
#  Feign Client开启日志
  logging:
    level:
      com.xt.open.jmall.product.remote.feignclients.CartFeignClient: debug
  #okhttp启用（feign默认JDK的动态代理来生成RequestTemplate）
  #okhttp:
    #enabled: true
#  httpclient启用
  httpclient:
    connection-timeout: 20000
    connection-timer-repeat: 20000
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  #Feign支持对请求和响应进行GZIP压缩，以提高通信效率。（由于开启GZIP压缩之后，Feign之间的调用数据通过二进制协议进行传输，返回值需要修改为ResponseEntity<byte[]>才可以正常显示，否则会导致服务之间的调用乱码。）
#  compression:
#    request: #请求
#      enabled: true #开启
#      mime-types: text/xml,application/xml,application/json #开启支持压缩的MIME TYPE
#      min-request-size: 2048 #配置压缩数据大小的下限
#    response: #响应
#      enabled: true #开启响应GZIP压缩
#hystrix:
#  propagate:
#    request-attribute:
#      enabled: true
#  command:
#    #全局默认配置
#    default:
#      #线程隔离相关
#      execution:
#        timeout:
#          #是否给方法执行设置超时时间，默认为true。一般我们不要改。
#          enabled: true
#        isolation:
#          #配置请求隔离的方式，这里是默认的线程池方式。还有一种信号量的方式semaphore，使用比较少。
#          strategy: threadPool
#          thread:
#            #方式执行的超时时间，默认为1000毫秒，在实际场景中需要根据情况设置
#            timeoutInMilliseconds: 10000
#            #发生超时时是否中断方法的执行，默认值为true。不要改。
#            interruptOnTimeout: true
#            #是否在方法执行被取消时中断方法，默认值为false。没有实际意义，默认就好！
#            interruptOnCancel: false
#  circuitBreaker:   #熔断器相关配置
#    enabled: true   #是否启动熔断器，默认为true，false表示不要引入Hystrix。
#    requestVolumeThreshold: 20     #启用熔断器功能窗口时间内的最小请求数，假设我们设置的窗口时间为10秒，
#    sleepWindowInMilliseconds: 5000    #所以此配置的作用是指定熔断器打开后多长时间内允许一次请求尝试执行，官方默认配置为5秒。
#    errorThresholdPercentage: 50   #窗口时间内超过50%的请求失败后就会打开熔断器将后续请求快速失败掉,默认配置为50
#ribbon:
#  eager-load:
#    enabled: true
#  #说明：同一台实例的最大自动重试次数，默认为1次，不包括首次
#  MaxAutoRetries: 1
#  #说明：要重试的下一个实例的最大数量，默认为1，不包括第一次被调用的实例
#  MaxAutoRetriesNextServer: 1
#  #说明：是否所有的操作都重试，默认为true
#  OkToRetryOnAllOperations: true
#  #说明：从注册中心刷新服务器列表信息的时间间隔，默认为2000毫秒，即2秒
#  ServerListRefreshInterval: 2000
#  #说明：使用Apache HttpClient连接超时时间，单位为毫秒
#  ConnectTimeout: 3000
#  #说明：使用Apache HttpClient读取的超时时间，单位为毫秒
#  ReadTimeout: 3000


